-- Create table section -------------------------------------------------

-- Table <age_rating_system>
CREATE TABLE IF NOT EXISTS PUBLIC.age_rating_system (
    ars_id INTEGER generated BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    PRIMARY key (ars_id)
);

-- Table <film>
CREATE TABLE IF NOT EXISTS PUBLIC.film (
    film_id INTEGER generated BY DEFAULT AS IDENTITY,
    description VARCHAR(255),
    duration INTEGER NOT NULL,
    name VARCHAR(255),
    rate INTEGER,
    release_date TIMESTAMP,
    mpa_ars_id INTEGER,
    PRIMARY key (film_id)
);

-- Table <genre>
CREATE TABLE IF NOT EXISTS PUBLIC.genre (
    genre_id INTEGER generated BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    PRIMARY key (genre_id)
);

-- Table <user>
CREATE TABLE IF NOT EXISTS PUBLIC.user (
    user_id INTEGER generated BY DEFAULT AS IDENTITY,
    birthday TIMESTAMP,
    email VARCHAR(255),
    login VARCHAR(255),
    name VARCHAR(255),
    PRIMARY key (user_id)
);

-- Create linking table section -------------------------------------------------

-- Linking table <film_genres>
CREATE TABLE IF NOT EXISTS PUBLIC.film_genres (
    film_film_id INTEGER NOT NULL,
    genres_genre_id INTEGER NOT NULL,
    PRIMARY key (film_film_id, genres_genre_id)
);

-- Linking table <user_films_likes>
CREATE TABLE IF NOT EXISTS PUBLIC.user_films_likes (
    user_user_id INTEGER NOT NULL,
    films_likes_film_id INTEGER NOT NULL,
    PRIMARY key (user_user_id, films_likes_film_id)
);

-- Linking table <user_friends>
CREATE TABLE IF NOT EXISTS PUBLIC.user_friends (
    user_user_id INTEGER NOT NULL,
    friends_user_id INTEGER NOT NULL,
    PRIMARY key (user_user_id, friends_user_id)
);

-- Create foreign keys section -------------------------------------------------

-- Relationships link between <film> and <age_rating_system> tables
ALTER TABLE
    PUBLIC.film
ADD CONSTRAINT IF NOT EXISTS fk_film__age_rating_system
    FOREIGN key (mpa_ars_id) REFERENCES PUBLIC.age_rating_system;

-- Relationships link between <genre> and <film> tables in <film_genres> table
ALTER TABLE
    PUBLIC.film_genres
ADD CONSTRAINT IF NOT EXISTS fk_film_genres__genre
    FOREIGN key (genres_genre_id) REFERENCES PUBLIC.genre;

ALTER TABLE
    PUBLIC.film_genres
ADD CONSTRAINT IF NOT EXISTS fk_film_genres__film
    FOREIGN key (film_film_id) REFERENCES PUBLIC.film;

-- Relationships link between <film> and <user> tables in <user_films_likes> table
ALTER TABLE
    PUBLIC.user_films_likes
ADD CONSTRAINT IF NOT EXISTS fk_user_films_likes__film
    FOREIGN key (films_likes_film_id) REFERENCES PUBLIC.film;

ALTER TABLE
    PUBLIC.user_films_likes
ADD CONSTRAINT IF NOT EXISTS fk_user_films_likes__user
    FOREIGN key (user_user_id) REFERENCES PUBLIC.user;

-- Relationships link between <user> and <user> tables in <user_friends> table
ALTER TABLE
    PUBLIC.user_friends
ADD CONSTRAINT IF NOT EXISTS fk_user_friends__user_01
    FOREIGN key (friends_user_id) REFERENCES PUBLIC.user;

ALTER TABLE
    PUBLIC.user_friends
ADD CONSTRAINT IF NOT EXISTS fk_user_friends__user_02
    FOREIGN key (user_user_id) REFERENCES PUBLIC.user;

-- Mermaid section -------------------------------------------------

-- erDiagram
-- 
--     user_films_likes{
--         ~integer~ user_user_id
--         ~integer~ films_likes_film_id
--     }
-- 
--     age_rating_system{
--         ~integer~ ars_id ~varchar(255)~ name
--     }
-- 
--     user{
--         ~integer~ user_id
--         ~timestamp~ birthday
--         ~varchar(255)~ email
--         ~varchar(255)~ login
--         ~varchar(255)~ name
--     }
-- 
--     user_friends{
--         ~integer~ user_user_id
--         ~integer~ friends_user_id
--     }
-- 
--     film{
--         ~integer~ film_id
--         ~varchar(255)~ description
--         ~integer~ duration
--         ~varchar(255)~ name
--         ~integer~ rate
--         ~timestamp~ release_date
--         ~integer~ mpa_ars_id
--     }
-- 
--     film_genres{
--         ~integer~ film_film_id
--         ~integer~ genres_genre_id
--     }
-- 
--     genre{
--         ~integer~ genre_id
--         ~varchar(255)~ name
--     }
-- 
--     film }|..|| age_rating_system : fk_film__age_rating_system
--     film_genres }|..|| genre : fk_film_genres__genre
--     film_genres }|..|| film : fk_film_genres__film
--     user_films_likes }|..|| film : fk_user_films_likes__film
--     user_films_likes }|..|| user : fk_user_films_likes__user
--     user_friends }|..|| user : fk_user_friends__user1
--     user_friends }|..|| user : fk_user_friends__user2